-
{'client_id': '67019', 'client_secret': '94bec5162fd0b13ed7e91e49e8344c8518bf22b5', 'refresh_token': 'c56e6c71dd4cf94a9987f8850f7210017b769570', 'grant_type': 'refresh_token'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.strava.com:443
DEBUG:urllib3.connectionpool:https://www.strava.com:443 "POST /oauth/token HTTP/1.1" 200 None
INFO:strava_client:Successfully refreshed Strava access token
ERROR:strava_client:Error checking rate limits: (sqlite3.OperationalError) no such column: strava_api_usage.requests_made
[SQL: SELECT strava_api_usage.id AS strava_api_usage_id, strava_api_usage.date AS strava_api_usage_date, strava_api_usage.requests_made AS strava_api_usage_requests_made, strava_api_usage.daily_limit AS strava_api_usage_daily_limit, strava_api_usage.last_sync_time AS strava_api_usage_last_sync_time, strava_api_usage.created_at AS strava_api_usage_created_at, strava_api_usage.updated_at AS strava_api_usage_updated_at 
FROM strava_api_usage 
WHERE strava_api_usage.date = ?
 LIMIT ? OFFSET ?]
[parameters: ('2025-06-04', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:strava_client:Error checking rate limits: (sqlite3.OperationalError) no such column: strava_api_usage.requests_made
[SQL: SELECT strava_api_usage.id AS strava_api_usage_id, strava_api_usage.date AS strava_api_usage_date, strava_api_usage.requests_made AS strava_api_usage_requests_made, strava_api_usage.daily_limit AS strava_api_usage_daily_limit, strava_api_usage.last_sync_time AS strava_api_usage_last_sync_time, strava_api_usage.created_at AS strava_api_usage_created_at, strava_api_usage.updated_at AS strava_api_usage_updated_at 
FROM strava_api_usage 
WHERE strava_api_usage.date = ?
 LIMIT ? OFFSET ?]
[parameters: ('2025-06-04', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.strava.com:443
DEBUG:urllib3.connectionpool:https://www.strava.com:443 "GET /api/v3/athlete/activities?after=1748908800&before=1748995200&per_page=200&page=1 HTTP/1.1" 200 None
ERROR:strava_client:Error recording request: (sqlite3.OperationalError) no such column: strava_api_usage.requests_made
[SQL: SELECT strava_api_usage.id AS strava_api_usage_id, strava_api_usage.date AS strava_api_usage_date, strava_api_usage.requests_made AS strava_api_usage_requests_made, strava_api_usage.daily_limit AS strava_api_usage_daily_limit, strava_api_usage.last_sync_time AS strava_api_usage_last_sync_time, strava_api_usage.created_at AS strava_api_usage_created_at, strava_api_usage.updated_at AS strava_api_usage_updated_at 
FROM strava_api_usage 
WHERE strava_api_usage.date = ?
 LIMIT ? OFFSET ?]
[parameters: ('2025-06-04', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
ERROR:strava_client:Error checking rate limits: (sqlite3.OperationalError) no such column: strava_api_usage.requests_made
[SQL: SELECT strava_api_usage.id AS strava_api_usage_id, strava_api_usage.date AS strava_api_usage_date, strava_api_usage.requests_made AS strava_api_usage_requests_made, strava_api_usage.daily_limit AS strava_api_usage_daily_limit, strava_api_usage.last_sync_time AS strava_api_usage_last_sync_time, strava_api_usage.created_at AS strava_api_usage_created_at, strava_api_usage.updated_at AS strava_api_usage_updated_at 
FROM strava_api_usage 
WHERE strava_api_usage.date = ?
 LIMIT ? OFFSET ?]
[parameters: ('2025-06-04', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): www.strava.com:443
DEBUG:urllib3.connectionpool:https://www.strava.com:443 "GET /api/v3/athlete/activities?after=1748908800&before=1748995200&per_page=200&page=2 HTTP/1.1" 200 None
ERROR:strava_client:Error recording request: (sqlite3.OperationalError) no such column: strava_api_usage.requests_made
[SQL: SELECT strava_api_usage.id AS strava_api_usage_id, strava_api_usage.date AS strava_api_usage_date, strava_api_usage.requests_made AS strava_api_usage_requests_made, strava_api_usage.daily_limit AS strava_api_usage_daily_limit, strava_api_usage.last_sync_time AS strava_api_usage_last_sync_time, strava_api_usage.created_at AS strava_api_usage_created_at, strava_api_usage.updated_at AS strava_api_usage_updated_at 
FROM strava_api_usage 
WHERE strava_api_usage.date = ?
 LIMIT ? OFFSET ?]
[parameters: ('2025-06-04', 1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
INFO:strava_client:Fetched 1 running activities
INFO:scheduler:Saved activity 14678647779 for athlete 1
INFO:scheduler:Processed 1 activities for athlete Rathish Padman
DEBUG:data_processor:Found planned workout: Distance: 5.0, Date: 2025-06-03 00:00:00
DEBUG:data_processor:Looking for activities on date 2025-06-03
DEBUG:data_processor:Found activity: Outdoor run, Date: 2025-06-03 06:39:54, Distance: 6.254
DEBUG:data_processor:Processing athlete 1 for date 2025-06-03
DEBUG:data_processor:Planned workout found: True
DEBUG:data_processor:Planned distance: 5.0
DEBUG:data_processor:Activities found: 1
DEBUG:data_processor:Found 1 activities for athlete 1 on 2025-06-03
INFO:data_processor:Processed daily performance for athlete 1: Over-performed
ERROR:data_processor:Error updating last sync time: (sqlite3.OperationalError) no such column: strava_api_usage.requests_made